sudo: required
services:
  - docker

before_install:
  - docker build -t eskimoquinn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run eskimoquinn/react-test npm test -- --coverage

after_success:
  - docker build -t eskimoquinn/multi-client ./client
  - docker build -t eskimoquinn/multi-nginx ./nginx
  - docker build -t eskimoquinn/multi-server ./server
  - docker build -t eskimoquinn/multi-worker ./worker